// bash_output — read accumulated output from a backgrounded bash job
// (fork-owned; extracted verbatim from bash.ts).

import { existsSync, statSync } from "node:fs";
import { join } from "node:path";
import type { AgentTool } from "@lue-labs/pi-agent-core";
import { StringEnum } from "@lue-labs/pi-ai";
import { type Static, Type } from "typebox";
import {
	BASH_MAX_OUTPUT_BYTES,
	type BashBgJob,
	type BashBgJobStore,
	bashBgLogDir,
	createBashBgJobStore,
	readBashBgLog,
} from "../bash-bg-jobs.ts";
import type { ToolDefinition } from "../extensions/types.ts";
import { wrapToolDefinition } from "./tool-definition-wrapper.ts";
import { formatSize } from "./truncate.ts";

export interface BashOutputToolDetails extends BashBgJob {
	fullOutputPath: string;
}

/**
 * Size of a background job's log file, or 0 when it cannot be stat'd.
 *
 * The log is written by a detached child and reaped independently, so it can be
 * absent, rotated, or replaced between the read and this call. The size is only
 * ever rendered into a status header, and every caller already prints the log
 * path beside it, so a missing file reads as "0.0 KB" rather than failing a
 * report the caller asked for.
 */
function bashBgLogSize(logPath: string): number {
	try {
		return statSync(logPath).size;
	} catch {
		return 0;
	}
}

/**
 * Render a background bash job's status header + bounded log slice — the body
 * of BashOutput, extracted so the task-registry seam (`core/tasks`) can reuse
 * the exact same bash rendering (tail/head/all
 * slicing, line caps, elapsed/size header) instead of reimplementing it.
 */
export function renderBashBgOutput(
	job: BashBgJob,
	options?: { mode?: "tail" | "head" | "all"; maxLines?: number },
): { text: string; fullOutputPath: string } {
	const { text, shownLines, totalLines, lineCountExact, truncated } = readBashBgLog(job, {
		mode: options?.mode ?? "tail",
		maxLines: options?.maxLines ?? 200,
	});
	const logSize = bashBgLogSize(job.logPath);
	const elapsed = ((job.endedAt ?? Date.now()) - job.startedAt) / 1000;
	const header =
		`bgId: ${job.id}\n` +
		`status: ${job.status}` +
		(job.status === "exited" ? ` (exit ${job.exitCode})` : "") +
		(job.status === "killed" && job.signal ? ` (${job.signal})` : "") +
		(job.status === "failed" && job.error ? ` (${job.error})` : "") +
		(job.lifecycle?.terminalReason ? `\nreason: ${job.lifecycle.terminalReason}` : "") +
		`\nelapsed: ${elapsed.toFixed(1)}s\n` +
		`log: ${job.logPath} (${(logSize / 1024).toFixed(1)} KB, ${lineCountExact ? totalLines : `at least ${totalLines}`} lines)` +
		(truncated
			? ` \u2014 showing ${shownLines}${lineCountExact ? ` of ${totalLines}` : "+"}, capped at ${formatSize(BASH_MAX_OUTPUT_BYTES)}`
			: "");
	const body = text || "(no output yet)";
	return { text: `${header}\n\n${body}`, fullOutputPath: job.logPath };
}

function bashBgLogPathForId(id: string): string | undefined {
	// Background ids are generated by nextBashBgId(). Keep this strict so a
	// missing registry entry can only map to the persisted bash-bg log directory,
	// never to an arbitrary caller-controlled path.
	if (!/^bg_[a-z0-9]+_[a-z0-9]+$/i.test(id)) return undefined;
	return join(bashBgLogDir(), `${id}.log`);
}

/**
 * Render a persisted background-bash log whose in-memory registry entry is gone.
 *
 * This happens after a pi process/session restart or registry drop: the bg job
 * log survives under ~/.pi/agent/bash-bg, but the task adapter can no longer
 * know pid/exit code/timing. Claude Code's useful part here is the graceful UX:
 * surface the surviving artifact plus the limitation, instead of returning only
 * "No background task" and forcing the user to rediscover the log by hand.
 */
export function renderOrphanedBashBgOutput(
	id: string,
	options?: { mode?: "tail" | "head" | "all"; maxLines?: number },
): { text: string; fullOutputPath: string } | undefined {
	const logPath = bashBgLogPathForId(id);
	if (!logPath || !existsSync(logPath)) return undefined;
	const job: BashBgJob = {
		id,
		command: "(unknown — registry entry missing)",
		cwd: "(unknown — registry entry missing)",
		pid: undefined,
		startedAt: 0,
		status: "failed",
		exitCode: null,
		signal: null,
		logPath,
		endedAt: undefined,
		error: "registry entry missing; process may have exited or pi may have restarted",
		lifecycle: {
			kind: "bash",
			outputBytes: 0,
			outputLimitBytes: 0,
			terminalReason: undefined,
			promptStalledAt: undefined,
			promptStallTail: undefined,
		},
	};
	const { text, shownLines, totalLines, lineCountExact, truncated } = readBashBgLog(job, {
		mode: options?.mode ?? "tail",
		maxLines: options?.maxLines ?? 200,
	});
	const logSize = bashBgLogSize(logPath);
	const header =
		`bgId: ${id}\n` +
		`status: registry-missing (persisted log found; exit status/pid unavailable)\n` +
		`log: ${logPath} (${(logSize / 1024).toFixed(1)} KB, ${lineCountExact ? totalLines : `at least ${totalLines}`} lines)` +
		(truncated
			? ` — showing ${shownLines}${lineCountExact ? ` of ${totalLines}` : "+"}, capped at ${formatSize(BASH_MAX_OUTPUT_BYTES)}`
			: "") +
		`\nnext: inspect the log above; if the command may still be running, verify externally (for example with ps) before restarting it.`;
	const body = text || "(log exists but has no output yet)";
	return { text: `${header}\n\n${body}`, fullOutputPath: logPath };
}

const bashOutputSchema = Type.Object({
	bgId: Type.String({ description: "Background job id returned by bash(run_in_background:true)." }),
	mode: Type.Optional(
		StringEnum(["tail", "head", "all"] as const, {
			description: "Which slice of the log to return. Default: tail.",
		}),
	),
	maxLines: Type.Optional(Type.Number({ description: "Maximum lines to return (default 200, hard cap 1000)." })),
});

export type BashOutputToolInput = Static<typeof bashOutputSchema>;

export function createBashOutputToolDefinition(options?: {
	toolName?: string;
	label?: string;
	jobs?: BashBgJobStore;
	alwaysLoad?: boolean;
}): ToolDefinition<typeof bashOutputSchema, BashOutputToolDetails | undefined> {
	const toolName = options?.toolName ?? "bash_output";
	const label = options?.label ?? "BashOutput";
	const jobs = options?.jobs ?? createBashBgJobStore();
	return {
		name: toolName,
		label,
		description:
			"Read accumulated stdout/stderr from a backgrounded bash job (started via bash with run_in_background:true). Returns a bounded slice of the log plus job status. Does not block or wait \u2014 just shows current state. Use this when you need to peek at progress or grab results after the job has completed. For live streaming with wake-on-output behavior, use monitor_start instead.",
		promptSnippet: "Read the log of a backgrounded bash job by bgId",
		alwaysLoad: options?.alwaysLoad,
		executionMode: "parallel",
		parameters: bashOutputSchema,
		async execute(_id, { bgId, mode, maxLines }) {
			const job = jobs.get(bgId);
			if (!job) {
				const orphaned = renderOrphanedBashBgOutput(bgId, { mode, maxLines });
				if (orphaned) {
					return {
						content: [{ type: "text", text: orphaned.text }],
						details: { bgId, fullOutputPath: orphaned.fullOutputPath } as unknown as BashOutputToolDetails,
					};
				}
				const known =
					jobs
						.list()
						.map((knownJob) => knownJob.id)
						.slice(-5)
						.join(", ") || "(none)";
				return {
					content: [{ type: "text", text: `No background bash job with bgId=${bgId}. Recent ids: ${known}` }],
					details: undefined,
				};
			}
			const rendered = renderBashBgOutput(job, { mode, maxLines });
			return {
				content: [{ type: "text", text: rendered.text }],
				details: { ...job, fullOutputPath: rendered.fullOutputPath },
			};
		},
	};
}

export function createBashOutputTool(): AgentTool<typeof bashOutputSchema> {
	return wrapToolDefinition(createBashOutputToolDefinition());
}

export function createBashOutputNativeToolDefinition(options?: {
	jobs?: BashBgJobStore;
	alwaysLoad?: boolean;
}): ToolDefinition<typeof bashOutputSchema, BashOutputToolDetails | undefined> {
	return createBashOutputToolDefinition({
		toolName: "BashOutput",
		label: "BashOutput",
		jobs: options?.jobs,
		alwaysLoad: options?.alwaysLoad,
	});
}

export function createBashOutputNativeTool(): AgentTool<typeof bashOutputSchema> {
	return wrapToolDefinition(createBashOutputNativeToolDefinition());
}
