import { type AgentMessage, uuidv7 } from "@valkyriweb/pi-agent-core";
import type {
	AssistantMessage,
	ImageContent,
	Message,
	StopReason,
	TextContent,
	ToolCall,
	ToolResultMessage,
	Usage,
} from "@valkyriweb/pi-ai";
import { randomUUID } from "crypto";
import {
	appendFileSync,
	closeSync,
	createReadStream,
	existsSync,
	mkdirSync,
	openSync,
	readdirSync,
	readSync,
	statSync,
	writeFileSync,
} from "fs";
import { readdir, stat } from "fs/promises";
import { join, resolve } from "path";
import { createInterface } from "readline";
import { StringDecoder } from "string_decoder";
import { getAgentDir as getDefaultAgentDir, getSessionsDir } from "../config.ts";
import { normalizePath, resolvePath } from "../utils/paths.ts";
import {
	type BashExecutionMessage,
	type CustomMessage,
	createBranchSummaryMessage,
	createCompactionSummaryMessage,
	createCustomMessage,
} from "./messages.ts";

export const CURRENT_SESSION_VERSION = 3;

export interface SessionHeader {
	type: "session";
	version?: number; // v1 sessions don't have this
	id: string;
	timestamp: string;
	cwd: string;
	parentSession?: string;
}

export interface NewSessionOptions {
	id?: string;
	parentSession?: string;
}

export interface SessionEntryBase {
	type: string;
	id: string;
	parentId: string | null;
	timestamp: string;
}

export interface SessionMessageEntry extends SessionEntryBase {
	type: "message";
	message: AgentMessage;
}

export interface ThinkingLevelChangeEntry extends SessionEntryBase {
	type: "thinking_level_change";
	thinkingLevel: string;
}

export interface ModelChangeEntry extends SessionEntryBase {
	type: "model_change";
	provider: string;
	modelId: string;
}

export interface CompactionEntry<T = unknown> extends SessionEntryBase {
	type: "compaction";
	summary: string;
	firstKeptEntryId: string;
	tokensBefore: number;
	/** Extension-specific data (e.g., ArtifactIndex, version markers for structured compaction) */
	details?: T;
	/** True if generated by an extension, undefined/false if pi-generated (backward compatible) */
	fromHook?: boolean;
}

export interface BranchSummaryEntry<T = unknown> extends SessionEntryBase {
	type: "branch_summary";
	fromId: string;
	summary: string;
	/** Extension-specific data (not sent to LLM) */
	details?: T;
	/** True if generated by an extension, false if pi-generated */
	fromHook?: boolean;
}

/**
 * Custom entry for extensions to store extension-specific data in the session.
 * Use customType to identify your extension's entries.
 *
 * Purpose: Persist extension state across session reloads. On reload, extensions can
 * scan entries for their customType and reconstruct internal state.
 *
 * Does NOT participate in LLM context (ignored by buildSessionContext).
 * For injecting content into context, see CustomMessageEntry.
 */
export interface CustomEntry<T = unknown> extends SessionEntryBase {
	type: "custom";
	customType: string;
	data?: T;
}

/** Label entry for user-defined bookmarks/markers on entries. */
export interface LabelEntry extends SessionEntryBase {
	type: "label";
	targetId: string;
	label: string | undefined;
}

/** Session metadata entry (e.g., user-defined display name). */
export interface SessionInfoEntry extends SessionEntryBase {
	type: "session_info";
	name?: string;
}

/**
 * Custom message entry for extensions to inject messages into LLM context.
 * Use customType to identify your extension's entries.
 *
 * Unlike CustomEntry, this DOES participate in LLM context.
 * The content is converted to a user message in buildSessionContext().
 * Use details for extension-specific metadata (not sent to LLM).
 *
 * display controls TUI rendering:
 * - false: hidden entirely
 * - true: rendered with distinct styling (different from user messages)
 */
export interface CustomMessageEntry<T = unknown> extends SessionEntryBase {
	type: "custom_message";
	customType: string;
	content: string | (TextContent | ImageContent)[];
	details?: T;
	display: boolean;
}

/** Session entry - has id/parentId for tree structure (returned by "read" methods in SessionManager) */
export type SessionEntry =
	| SessionMessageEntry
	| ThinkingLevelChangeEntry
	| ModelChangeEntry
	| CompactionEntry
	| BranchSummaryEntry
	| CustomEntry
	| CustomMessageEntry
	| LabelEntry
	| SessionInfoEntry;

/** Raw file entry (includes header) */
export type FileEntry = SessionHeader | SessionEntry;

/** Tree node for getTree() - defensive copy of session structure */
export interface SessionTreeNode {
	entry: SessionEntry;
	children: SessionTreeNode[];
	/** Resolved label for this entry, if any */
	label?: string;
	/** Timestamp of the latest label change for this entry, if any */
	labelTimestamp?: string;
}

export interface SessionContext {
	messages: AgentMessage[];
	thinkingLevel: string;
	model: { provider: string; modelId: string } | null;
}

export interface ResidentPruneOptions {
	/** Stub summarized pre-compaction session entries in resident memory. Durable JSONL is not rewritten. */
	stubSummarizedEntries?: boolean;
	/** Stub old tool-result payloads only when their tool-call pair is also summarized. */
	stubToolResults?: boolean;
}

export interface ResidentPruneResult {
	compactionId: string | undefined;
	firstKeptEntryId: string | undefined;
	entriesVisited: number;
	entriesStubbed: number;
	protectedEntries: number;
	payloadBytesBefore: number;
	payloadBytesAfter: number;
	payloadBytesFreed: number;
	jsonlUnchanged: true;
}

export interface SessionHydrationOptions {
	/** Stub summarized pre-compaction payloads while hydrating existing sessions. Durable JSONL is not rewritten. */
	residentPrune?: boolean;
	residentPruneOptions?: ResidentPruneOptions;
}

export interface LoadEntriesFromFileOptions {
	/** Stub summarized pre-compaction payloads before retaining parsed entries. Durable JSONL is not rewritten. */
	residentPrune?: boolean;
	residentPruneOptions?: ResidentPruneOptions;
}

export interface SessionInfo {
	path: string;
	id: string;
	/** Working directory where the session was started. Empty string for old sessions. */
	cwd: string;
	/** User-defined display name from session_info entries. */
	name?: string;
	/** Path to the parent session (if this session was forked). */
	parentSessionPath?: string;
	created: Date;
	modified: Date;
	messageCount: number;
	firstMessage: string;
	allMessagesText: string;
}

export type ReadonlySessionManager = Pick<
	SessionManager,
	| "getCwd"
	| "getSessionDir"
	| "getSessionId"
	| "getSessionFile"
	| "getLeafId"
	| "getLeafEntry"
	| "getEntry"
	| "getLabel"
	| "getBranch"
	| "getHeader"
	| "getEntries"
	| "getTree"
	| "getSessionName"
>;

function createSessionId(): string {
	return uuidv7();
}

export function assertValidSessionId(id: string): void {
	if (!/^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$/.test(id)) {
		throw new Error(
			"Session id must be non-empty, contain only alphanumeric characters, '-', '_', and '.', and start and end with an alphanumeric character",
		);
	}
}

/** Generate a unique short ID (8 hex chars, collision-checked) */
function generateId(byId: { has(id: string): boolean }): string {
	for (let i = 0; i < 100; i++) {
		const id = randomUUID().slice(0, 8);
		if (!byId.has(id)) return id;
	}
	// Fallback to full UUID if somehow we have collisions
	return randomUUID();
}

/** Migrate v1 → v2: add id/parentId tree structure. Mutates in place. */
function migrateV1ToV2(entries: FileEntry[]): void {
	const ids = new Set<string>();
	let prevId: string | null = null;

	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 2;
			continue;
		}

		entry.id = generateId(ids);
		entry.parentId = prevId;
		prevId = entry.id;

		// Convert firstKeptEntryIndex to firstKeptEntryId for compaction
		if (entry.type === "compaction") {
			const comp = entry as CompactionEntry & { firstKeptEntryIndex?: number };
			if (typeof comp.firstKeptEntryIndex === "number") {
				const targetEntry = entries[comp.firstKeptEntryIndex];
				if (targetEntry && targetEntry.type !== "session") {
					comp.firstKeptEntryId = targetEntry.id;
				}
				delete comp.firstKeptEntryIndex;
			}
		}
	}
}

/** Migrate v2 → v3: rename hookMessage role to custom. Mutates in place. */
function migrateV2ToV3(entries: FileEntry[]): void {
	for (const entry of entries) {
		if (entry.type === "session") {
			entry.version = 3;
			continue;
		}

		// Update message entries with hookMessage role
		if (entry.type === "message") {
			const msgEntry = entry as SessionMessageEntry;
			if (msgEntry.message && (msgEntry.message as { role: string }).role === "hookMessage") {
				(msgEntry.message as { role: string }).role = "custom";
			}
		}
	}
}

/**
 * Run all necessary migrations to bring entries to current version.
 * Mutates entries in place. Returns true if any migration was applied.
 */
function migrateToCurrentVersion(entries: FileEntry[]): boolean {
	const header = entries.find((e) => e.type === "session") as SessionHeader | undefined;
	const version = header?.version ?? 1;

	if (version >= CURRENT_SESSION_VERSION) return false;

	if (version < 2) migrateV1ToV2(entries);
	if (version < 3) migrateV2ToV3(entries);

	return true;
}

/** Exported for testing */
export function migrateSessionEntries(entries: FileEntry[]): void {
	migrateToCurrentVersion(entries);
}

/** Exported for compaction.test.ts */
export function parseSessionEntries(content: string): FileEntry[] {
	const entries: FileEntry[] = [];
	const lines = content.trim().split("\n");

	for (const line of lines) {
		if (!line.trim()) continue;
		try {
			const entry = JSON.parse(line) as FileEntry;
			entries.push(entry);
		} catch {
			// Skip malformed lines
		}
	}

	return entries;
}

export function getLatestCompactionEntry(entries: SessionEntry[]): CompactionEntry | null {
	for (let i = entries.length - 1; i >= 0; i--) {
		if (entries[i].type === "compaction") {
			return entries[i] as CompactionEntry;
		}
	}
	return null;
}

/**
 * Build the session context from entries using tree traversal.
 * If leafId is provided, walks from that entry to root.
 * Handles compaction and branch summaries along the path.
 */
export function buildSessionContext(
	entries: SessionEntry[],
	leafId?: string | null,
	byId?: Map<string, SessionEntry>,
): SessionContext {
	// Build uuid index if not available
	if (!byId) {
		byId = new Map<string, SessionEntry>();
		for (const entry of entries) {
			byId.set(entry.id, entry);
		}
	}

	// Find leaf
	let leaf: SessionEntry | undefined;
	if (leafId === null) {
		// Explicitly null - return no messages (navigated to before first entry)
		return { messages: [], thinkingLevel: "off", model: null };
	}
	if (leafId) {
		leaf = byId.get(leafId);
	}
	if (!leaf) {
		// Fallback to last entry (when leafId is undefined)
		leaf = entries[entries.length - 1];
	}

	if (!leaf) {
		return { messages: [], thinkingLevel: "off", model: null };
	}

	// Walk from leaf to root, collecting path
	const path: SessionEntry[] = [];
	let current: SessionEntry | undefined = leaf;
	while (current) {
		path.push(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}
	path.reverse();

	// Extract settings and find compaction
	let thinkingLevel = "off";
	let model: { provider: string; modelId: string } | null = null;
	let compaction: CompactionEntry | null = null;

	for (const entry of path) {
		if (entry.type === "thinking_level_change") {
			thinkingLevel = entry.thinkingLevel;
		} else if (entry.type === "model_change") {
			model = { provider: entry.provider, modelId: entry.modelId };
		} else if (entry.type === "message" && entry.message.role === "assistant") {
			model = { provider: entry.message.provider, modelId: entry.message.model };
		} else if (entry.type === "compaction") {
			compaction = entry;
		}
	}

	// Build messages and collect corresponding entries
	// When there's a compaction, we need to:
	// 1. Emit summary first (entry = compaction)
	// 2. Emit kept messages (from firstKeptEntryId up to compaction)
	// 3. Emit messages after compaction
	const messages: AgentMessage[] = [];

	const appendMessage = (entry: SessionEntry) => {
		if (entry.type === "message") {
			messages.push(entry.message);
		} else if (entry.type === "custom_message") {
			messages.push(
				createCustomMessage(entry.customType, entry.content, entry.display, entry.details, entry.timestamp),
			);
		} else if (entry.type === "branch_summary" && entry.summary) {
			messages.push(createBranchSummaryMessage(entry.summary, entry.fromId, entry.timestamp));
		}
	};

	if (compaction) {
		// Emit summary first
		messages.push(createCompactionSummaryMessage(compaction.summary, compaction.tokensBefore, compaction.timestamp));

		// Find compaction index in path
		const compactionIdx = path.findIndex((e) => e.type === "compaction" && e.id === compaction.id);

		// Emit kept messages (before compaction, starting from firstKeptEntryId)
		let foundFirstKept = false;
		for (let i = 0; i < compactionIdx; i++) {
			const entry = path[i];
			if (entry.id === compaction.firstKeptEntryId) {
				foundFirstKept = true;
			}
			if (foundFirstKept) {
				appendMessage(entry);
			}
		}

		// Emit messages after compaction
		for (let i = compactionIdx + 1; i < path.length; i++) {
			const entry = path[i];
			appendMessage(entry);
		}
	} else {
		// No compaction - emit all messages, handle branch summaries and custom messages
		for (const entry of path) {
			appendMessage(entry);
		}
	}

	return { messages, thinkingLevel, model };
}

const RESIDENT_PRUNED_TEXT =
	"[Resident session payload pruned after compaction; full content remains in the durable session transcript.]";

function jsonByteLength(value: unknown): number {
	if (value === undefined) return 0;
	try {
		return Buffer.byteLength(JSON.stringify(value), "utf8");
	} catch {
		return Buffer.byteLength(String(value), "utf8");
	}
}

function estimateEntryPayloadBytes(entry: SessionEntry): number {
	switch (entry.type) {
		case "message":
			return jsonByteLength(entry.message);
		case "custom_message":
			return jsonByteLength(entry.content) + jsonByteLength(entry.details);
		case "custom":
			return jsonByteLength(entry.data);
		case "compaction":
			return jsonByteLength(entry.summary) + jsonByteLength(entry.details);
		case "branch_summary":
			return jsonByteLength(entry.summary) + jsonByteLength(entry.details);
		case "label":
			return jsonByteLength(entry.label);
		case "model_change":
			return jsonByteLength(entry.provider) + jsonByteLength(entry.modelId);
		case "thinking_level_change":
			return jsonByteLength(entry.thinkingLevel);
		case "session_info":
			return jsonByteLength(entry.name);
	}
}

export function estimateResidentPayloadBytes(entries: SessionEntry[]): number {
	return entries.reduce((total, entry) => total + estimateEntryPayloadBytes(entry), 0);
}

function isAssistantMessage(message: AgentMessage): message is AssistantMessage {
	return message.role === "assistant";
}

function isToolResultMessage(message: AgentMessage): message is ToolResultMessage {
	return message.role === "toolResult";
}

function toolCallsForEntry(entry: SessionEntry): ToolCall[] {
	if (entry.type !== "message" || !isAssistantMessage(entry.message) || !Array.isArray(entry.message.content))
		return [];
	return entry.message.content.filter((block): block is ToolCall => block.type === "toolCall");
}

function collectToolPairEntryIds(path: SessionEntry[]): {
	toolCallEntryIds: Map<string, string>;
	toolResultEntryIds: Map<string, string>;
} {
	const toolCallEntryIds = new Map<string, string>();
	const toolResultEntryIds = new Map<string, string>();
	for (const entry of path) {
		if (entry.type !== "message") continue;
		for (const toolCall of toolCallsForEntry(entry)) {
			toolCallEntryIds.set(toolCall.id, entry.id);
		}
		if (isToolResultMessage(entry.message)) {
			toolResultEntryIds.set(entry.message.toolCallId, entry.id);
		}
	}
	return { toolCallEntryIds, toolResultEntryIds };
}

function entryHasProtectedToolPair(
	entry: SessionEntry,
	candidateIds: ReadonlySet<string>,
	toolPairs: ReturnType<typeof collectToolPairEntryIds>,
): boolean {
	if (entry.type !== "message") return false;
	if (isAssistantMessage(entry.message)) {
		for (const toolCall of toolCallsForEntry(entry)) {
			const toolResultEntryId = toolPairs.toolResultEntryIds.get(toolCall.id);
			if (!toolResultEntryId || !candidateIds.has(toolResultEntryId)) {
				return true;
			}
		}
	}
	if (isToolResultMessage(entry.message)) {
		const toolCallEntryId = toolPairs.toolCallEntryIds.get(entry.message.toolCallId);
		if (!toolCallEntryId || !candidateIds.has(toolCallEntryId)) {
			return true;
		}
	}
	return false;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null && !Array.isArray(value);
}

function keepRecoverableDetails(details: unknown): Record<string, unknown> | undefined {
	if (!isRecord(details)) return undefined;
	const retained: Record<string, unknown> = {};
	for (const key of ["recoverableOutput", "fullOutputPath", "outputPath", "outputFile", "rawOutputPath"]) {
		if (key in details) {
			retained[key] = details[key];
		}
	}
	return Object.keys(retained).length > 0 ? retained : undefined;
}

function stubUserContent(content: string | (TextContent | ImageContent)[]): string | TextContent[] {
	if (typeof content === "string") return RESIDENT_PRUNED_TEXT;
	return [{ type: "text", text: RESIDENT_PRUNED_TEXT }];
}

function stubAssistantMessage(message: AssistantMessage): AssistantMessage {
	if (!Array.isArray(message.content)) {
		return { ...message, content: [{ type: "text", text: RESIDENT_PRUNED_TEXT }] };
	}
	return {
		...message,
		content: message.content.map((block) => {
			if (block.type === "toolCall") {
				return { type: "toolCall", id: block.id, name: block.name, arguments: { residentPruned: true } };
			}
			if (block.type === "thinking") {
				return { type: "thinking", thinking: RESIDENT_PRUNED_TEXT };
			}
			if (block.type === "tool_reference") {
				return block;
			}
			return { type: "text", text: RESIDENT_PRUNED_TEXT };
		}),
	};
}

function stubToolResultMessage(message: ToolResultMessage): ToolResultMessage {
	return {
		...message,
		content: [{ type: "text", text: RESIDENT_PRUNED_TEXT }],
		details: keepRecoverableDetails(message.details),
	};
}

function stubSessionMessage(message: AgentMessage): AgentMessage {
	if (message.role === "user") {
		return { ...message, content: stubUserContent(message.content) };
	}
	if (isAssistantMessage(message)) {
		return stubAssistantMessage(message);
	}
	if (isToolResultMessage(message)) {
		return stubToolResultMessage(message);
	}
	if (message.role === "bashExecution") {
		return { ...message, output: RESIDENT_PRUNED_TEXT };
	}
	if (message.role === "custom") {
		return {
			...message,
			content: stubUserContent(message.content),
			details: keepRecoverableDetails(message.details),
		};
	}
	return message;
}

function stubResidentEntryPayload(entry: SessionEntry, options: Required<ResidentPruneOptions>): boolean {
	if (entry.type === "message") {
		if (!options.stubToolResults && isToolResultMessage(entry.message)) return false;
		entry.message = stubSessionMessage(entry.message);
		return true;
	}
	if (entry.type === "custom_message" && options.stubSummarizedEntries) {
		entry.content = stubUserContent(entry.content);
		entry.details = keepRecoverableDetails(entry.details);
		return true;
	}
	if (entry.type === "branch_summary" && options.stubSummarizedEntries) {
		entry.summary = RESIDENT_PRUNED_TEXT;
		entry.details = keepRecoverableDetails(entry.details);
		return true;
	}
	if (entry.type === "compaction" && options.stubSummarizedEntries) {
		entry.summary = RESIDENT_PRUNED_TEXT;
		entry.details = keepRecoverableDetails(entry.details);
		return true;
	}
	return false;
}

/**
 * Compute the default session directory for a cwd.
 * Encodes cwd into a safe directory name under ~/.pi/agent/sessions/.
 */
function getDefaultSessionDirPath(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const resolvedCwd = resolvePath(cwd);
	const resolvedAgentDir = resolvePath(agentDir);
	const safePath = `--${resolvedCwd.replace(/^[/\\]/, "").replace(/[/\\:]/g, "-")}--`;
	return join(resolvedAgentDir, "sessions", safePath);
}

export function getDefaultSessionDir(cwd: string, agentDir: string = getDefaultAgentDir()): string {
	const sessionDir = getDefaultSessionDirPath(cwd, agentDir);
	if (!existsSync(sessionDir)) {
		mkdirSync(sessionDir, { recursive: true });
	}
	return sessionDir;
}

const SESSION_READ_BUFFER_SIZE = 1024 * 1024;

function parseSessionEntryLine(line: string): FileEntry | null {
	if (!line.trim()) return null;
	try {
		return JSON.parse(line) as FileEntry;
	} catch {
		// Skip malformed lines
		return null;
	}
}

function readSessionFileLines(filePath: string, onLine: (line: string) => void): void {
	const fd = openSync(filePath, "r");
	try {
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(SESSION_READ_BUFFER_SIZE);
		let pending = "";

		while (true) {
			const bytesRead = readSync(fd, buffer, 0, buffer.length, null);
			if (bytesRead === 0) break;

			pending += decoder.write(buffer.subarray(0, bytesRead));
			let lineStart = 0;
			let newlineIndex = pending.indexOf("\n", lineStart);
			while (newlineIndex !== -1) {
				onLine(pending.slice(lineStart, newlineIndex));
				lineStart = newlineIndex + 1;
				newlineIndex = pending.indexOf("\n", lineStart);
			}
			pending = pending.slice(lineStart);
		}

		pending += decoder.end();
		if (pending.trim()) onLine(pending);
	} finally {
		closeSync(fd);
	}
}

type SessionEntryMetadata = {
	id: string;
	parentId: string | null;
	type: SessionEntry["type"];
	timestamp: string;
	firstKeptEntryId?: string;
	tokensBefore?: number;
	messageRole?: string;
	api?: string;
	provider?: string;
	model?: string;
	stopReason?: string;
	isError?: boolean;
	customType?: string;
	display?: boolean;
	fromId?: string;
	command?: string;
	toolCallIds: string[];
	toolResultCallId?: string;
	toolName?: string;
};

type ResidentLoadPrunePlan = {
	candidateIds: Set<string>;
	protectedIds: Set<string>;
	rawStubs: Map<string, SessionEntry>;
};

const JSON_STRING_VALUE = String.raw`"((?:[^"\\]|\\.)*)"`;

function decodeJsonStringLiteral(raw: string | undefined): string | undefined {
	if (raw === undefined) return undefined;
	try {
		return JSON.parse(`"${raw}"`) as string;
	} catch {
		return undefined;
	}
}

function extractJsonStringField(line: string, field: string): string | undefined {
	const match = new RegExp(String.raw`"${field}"\s*:\s*${JSON_STRING_VALUE}`).exec(line);
	return decodeJsonStringLiteral(match?.[1]);
}

function extractLastJsonStringField(line: string, field: string): string | undefined {
	const matches = [...line.matchAll(new RegExp(String.raw`"${field}"\s*:\s*${JSON_STRING_VALUE}`, "g"))];
	return decodeJsonStringLiteral(matches.at(-1)?.[1]);
}

function extractJsonNullableStringField(line: string, field: string): string | null | undefined {
	const match = new RegExp(String.raw`"${field}"\s*:\s*(null|${JSON_STRING_VALUE})`).exec(line);
	if (!match) return undefined;
	if (match[1] === "null") return null;
	return decodeJsonStringLiteral(match[2]);
}

function extractJsonNumberField(line: string, field: string): number | undefined {
	const match = new RegExp(String.raw`"${field}"\s*:\s*(-?\d+(?:\.\d+)?)`).exec(line);
	if (!match) return undefined;
	const value = Number(match[1]);
	return Number.isFinite(value) ? value : undefined;
}

function extractJsonBooleanField(line: string, field: string): boolean | undefined {
	const match = new RegExp(String.raw`"${field}"\s*:\s*(true|false)`).exec(line);
	if (!match) return undefined;
	return match[1] === "true";
}

function isSessionEntryType(type: string | undefined): type is SessionEntry["type"] {
	return (
		type === "message" ||
		type === "thinking_level_change" ||
		type === "model_change" ||
		type === "compaction" ||
		type === "branch_summary" ||
		type === "custom" ||
		type === "custom_message" ||
		type === "label" ||
		type === "session_info"
	);
}

function extractMessageRole(line: string): string | undefined {
	const match = new RegExp(String.raw`"message"\s*:\s*\{\s*"role"\s*:\s*${JSON_STRING_VALUE}`).exec(line);
	return decodeJsonStringLiteral(match?.[1]);
}

function extractToolCallIds(line: string): string[] {
	const ids: string[] = [];
	const matches = line.matchAll(/"type"\s*:\s*"toolCall"/g);
	for (const match of matches) {
		const start = match.index ?? 0;
		const nearbyObject = line.slice(start, Math.min(line.length, start + 2048));
		const id = extractJsonStringField(nearbyObject, "id");
		if (id) ids.push(id);
	}
	return ids;
}

function metadataForSessionLine(line: string): SessionEntryMetadata | "session" | undefined {
	const trimmed = line.trim();
	if (!trimmed) return undefined;
	const type = extractJsonStringField(trimmed, "type");
	if (type === "session") return "session";
	if (!isSessionEntryType(type)) return undefined;

	const id = extractJsonStringField(trimmed, "id");
	const parentId = extractJsonNullableStringField(trimmed, "parentId");
	const timestamp = extractJsonStringField(trimmed, "timestamp");
	if (!id || parentId === undefined || !timestamp) return undefined;

	return {
		id,
		parentId,
		type,
		timestamp,
		firstKeptEntryId: type === "compaction" ? extractJsonStringField(trimmed, "firstKeptEntryId") : undefined,
		tokensBefore: type === "compaction" ? extractJsonNumberField(trimmed, "tokensBefore") : undefined,
		messageRole: type === "message" ? extractMessageRole(trimmed) : undefined,
		api: type === "message" ? extractJsonStringField(trimmed, "api") : undefined,
		provider: type === "message" ? extractLastJsonStringField(trimmed, "provider") : undefined,
		model: type === "message" ? extractLastJsonStringField(trimmed, "model") : undefined,
		stopReason: type === "message" ? extractJsonStringField(trimmed, "stopReason") : undefined,
		isError: type === "message" ? extractJsonBooleanField(trimmed, "isError") : undefined,
		customType:
			type === "message" || type === "custom" || type === "custom_message"
				? extractJsonStringField(trimmed, "customType")
				: undefined,
		display:
			type === "message" || type === "custom_message" ? extractJsonBooleanField(trimmed, "display") : undefined,
		fromId: type === "branch_summary" ? extractJsonStringField(trimmed, "fromId") : undefined,
		command: type === "message" ? extractJsonStringField(trimmed, "command") : undefined,
		toolCallIds: type === "message" ? extractToolCallIds(trimmed) : [],
		toolResultCallId: type === "message" ? extractJsonStringField(trimmed, "toolCallId") : undefined,
		toolName: type === "message" ? extractJsonStringField(trimmed, "toolName") : undefined,
	};
}

function metadataTimestampMs(metadata: SessionEntryMetadata): number {
	const value = Date.parse(metadata.timestamp);
	return Number.isFinite(value) ? value : Date.now();
}

function rawStubContent(): TextContent[] {
	return [{ type: "text", text: RESIDENT_PRUNED_TEXT }];
}

function zeroUsage(): Usage {
	return {
		input: 0,
		output: 0,
		cacheRead: 0,
		cacheWrite: 0,
		totalTokens: 0,
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0, total: 0 },
	};
}

function isStopReason(value: string | undefined): value is StopReason {
	return value === "stop" || value === "length" || value === "toolUse" || value === "error" || value === "aborted";
}

function rawAssistantStopReason(metadata: SessionEntryMetadata): StopReason {
	if (isStopReason(metadata.stopReason)) return metadata.stopReason;
	return metadata.toolCallIds.length > 0 ? "toolUse" : "stop";
}

function stubEntryFromRawMetadata(
	metadata: SessionEntryMetadata,
	options: Required<ResidentPruneOptions>,
): SessionEntry | undefined {
	const base = { id: metadata.id, parentId: metadata.parentId, timestamp: metadata.timestamp };
	const timestamp = metadataTimestampMs(metadata);

	if (metadata.type === "message") {
		if (metadata.messageRole === "user") {
			return {
				...base,
				type: "message",
				message: { role: "user", content: rawStubContent(), timestamp } as AgentMessage,
			};
		}
		if (metadata.messageRole === "assistant") {
			if (!metadata.api || !metadata.provider || !metadata.model) return undefined;
			const toolCalls = metadata.toolCallIds.map((id) => ({
				type: "toolCall" as const,
				id,
				name: "resident_pruned",
				arguments: { residentPruned: true },
			}));
			return {
				...base,
				type: "message",
				message: {
					role: "assistant",
					content: [...rawStubContent(), ...toolCalls],
					api: metadata.api,
					provider: metadata.provider,
					model: metadata.model,
					usage: zeroUsage(),
					stopReason: rawAssistantStopReason(metadata),
					timestamp,
				} as AgentMessage,
			};
		}
		if (metadata.messageRole === "toolResult") {
			if (!options.stubToolResults || !metadata.toolResultCallId) return undefined;
			return {
				...base,
				type: "message",
				message: {
					role: "toolResult",
					toolCallId: metadata.toolResultCallId,
					toolName: metadata.toolName ?? "resident_pruned",
					content: rawStubContent(),
					isError: metadata.isError ?? false,
					timestamp,
				} as AgentMessage,
			};
		}
		if (metadata.messageRole === "bashExecution") {
			return {
				...base,
				type: "message",
				message: {
					role: "bashExecution",
					command: metadata.command ?? "resident-pruned",
					output: RESIDENT_PRUNED_TEXT,
					exitCode: undefined,
					cancelled: false,
					truncated: true,
					timestamp,
				} as BashExecutionMessage,
			};
		}
		if (metadata.messageRole === "custom") {
			return {
				...base,
				type: "message",
				message: {
					role: "custom",
					customType: metadata.customType ?? "resident_pruned",
					content: rawStubContent(),
					display: metadata.display ?? false,
					timestamp,
				} as CustomMessage,
			};
		}
		return undefined;
	}

	if (metadata.type === "custom_message" && options.stubSummarizedEntries) {
		return {
			...base,
			type: "custom_message",
			customType: metadata.customType ?? "resident_pruned",
			content: rawStubContent(),
			display: metadata.display ?? false,
		};
	}
	if (metadata.type === "branch_summary" && options.stubSummarizedEntries && metadata.fromId) {
		return { ...base, type: "branch_summary", fromId: metadata.fromId, summary: RESIDENT_PRUNED_TEXT };
	}
	if (metadata.type === "compaction" && options.stubSummarizedEntries && metadata.firstKeptEntryId) {
		return {
			...base,
			type: "compaction",
			summary: RESIDENT_PRUNED_TEXT,
			firstKeptEntryId: metadata.firstKeptEntryId,
			tokensBefore: metadata.tokensBefore ?? 0,
		};
	}

	return undefined;
}

function buildResidentLoadPrunePlan(
	filePath: string,
	options: Required<ResidentPruneOptions>,
): ResidentLoadPrunePlan | undefined {
	const metadata: SessionEntryMetadata[] = [];
	const byId = new Map<string, SessionEntryMetadata>();
	const toolCallEntryIds = new Map<string, string>();
	const toolResultEntryIds = new Map<string, string>();
	let sawInvalidMetadata = false;

	readSessionFileLines(filePath, (line) => {
		const item = metadataForSessionLine(line);
		if (item === "session") return;
		if (!item) {
			if (line.trim()) sawInvalidMetadata = true;
			return;
		}
		metadata.push(item);
		byId.set(item.id, item);
		for (const toolCallId of item.toolCallIds) {
			toolCallEntryIds.set(toolCallId, item.id);
		}
		if (item.toolResultCallId) {
			toolResultEntryIds.set(item.toolResultCallId, item.id);
		}
	});
	if (sawInvalidMetadata) return undefined;

	const leaf = metadata.at(-1);
	if (!leaf) return undefined;

	const path: SessionEntryMetadata[] = [];
	let current: SessionEntryMetadata | undefined = leaf;
	while (current) {
		path.unshift(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}

	let compactionIndex = -1;
	for (let i = path.length - 1; i >= 0; i--) {
		if (path[i].type === "compaction") {
			compactionIndex = i;
			break;
		}
	}
	const compaction = path[compactionIndex];
	if (!compaction?.firstKeptEntryId) return undefined;

	const firstKeptIndex = path.findIndex((entry) => entry.id === compaction.firstKeptEntryId);
	if (firstKeptIndex < 0 || firstKeptIndex >= compactionIndex) return undefined;

	const candidates = path.slice(0, firstKeptIndex);
	const candidateIds = new Set(candidates.map((entry) => entry.id));
	const protectedIds = new Set<string>();

	for (const entry of candidates) {
		for (const toolCallId of entry.toolCallIds) {
			const toolResultEntryId = toolResultEntryIds.get(toolCallId);
			if (!toolResultEntryId || !candidateIds.has(toolResultEntryId)) {
				protectedIds.add(entry.id);
			}
		}
		if (entry.toolResultCallId) {
			const toolCallEntryId = toolCallEntryIds.get(entry.toolResultCallId);
			if (!toolCallEntryId || !candidateIds.has(toolCallEntryId)) {
				protectedIds.add(entry.id);
			}
		}
	}

	const rawStubs = new Map<string, SessionEntry>();
	for (const entry of candidates) {
		if (protectedIds.has(entry.id)) continue;
		const stub = stubEntryFromRawMetadata(entry, options);
		if (stub) rawStubs.set(entry.id, stub);
	}

	return { candidateIds, protectedIds, rawStubs };
}

function hasValidSessionHeader(entries: FileEntry[]): boolean {
	if (entries.length === 0) return true;
	const header = entries[0];
	return header.type === "session" && typeof (header as { id?: unknown }).id === "string";
}

function buildBranchFromEntries(entries: FileEntry[], leafId: string): SessionEntry[] | undefined {
	const byId = new Map<string, SessionEntry>();
	for (const entry of entries) {
		if (entry.type !== "session") byId.set(entry.id, entry);
	}
	const path: SessionEntry[] = [];
	let current = byId.get(leafId);
	if (!current) return undefined;
	while (current) {
		path.unshift(current);
		current = current.parentId ? byId.get(current.parentId) : undefined;
	}
	return path;
}

/** Exported for testing */
export function loadEntriesFromFile(filePath: string, options: LoadEntriesFromFileOptions = {}): FileEntry[] {
	const resolvedFilePath = normalizePath(filePath);
	if (!existsSync(resolvedFilePath)) return [];

	const pruneOptions: Required<ResidentPruneOptions> = {
		stubSummarizedEntries: options.residentPruneOptions?.stubSummarizedEntries ?? true,
		stubToolResults: options.residentPruneOptions?.stubToolResults ?? true,
	};
	const prunePlan = options.residentPrune ? buildResidentLoadPrunePlan(resolvedFilePath, pruneOptions) : undefined;
	const entries: FileEntry[] = [];

	readSessionFileLines(resolvedFilePath, (line) => {
		const metadata = prunePlan ? metadataForSessionLine(line) : undefined;
		if (metadata && metadata !== "session") {
			const stub = prunePlan?.rawStubs.get(metadata.id);
			if (stub) {
				entries.push(stub);
				return;
			}
		}

		const entry = parseSessionEntryLine(line);
		if (!entry) return;
		if (
			prunePlan &&
			entry.type !== "session" &&
			prunePlan.candidateIds.has(entry.id) &&
			!prunePlan.protectedIds.has(entry.id)
		) {
			stubResidentEntryPayload(entry, pruneOptions);
		}
		entries.push(entry);
	});

	return hasValidSessionHeader(entries) ? entries : [];
}

const MAX_SESSION_HEADER_BYTES = 64 * 1024;

function readSessionHeader(filePath: string): SessionHeader | null {
	let fd: number | undefined;
	try {
		fd = openSync(filePath, "r");
		const decoder = new StringDecoder("utf8");
		const buffer = Buffer.allocUnsafe(Math.min(8192, MAX_SESSION_HEADER_BYTES));
		let position = 0;
		let pending = "";

		while (position < MAX_SESSION_HEADER_BYTES) {
			const bytesToRead = Math.min(buffer.length, MAX_SESSION_HEADER_BYTES - position);
			const bytesRead = readSync(fd, buffer, 0, bytesToRead, position);
			if (bytesRead === 0) break;
			position += bytesRead;
			pending += decoder.write(buffer.subarray(0, bytesRead));
			const newlineIndex = pending.indexOf("\n");
			if (newlineIndex !== -1) {
				pending = pending.slice(0, newlineIndex);
				break;
			}
		}

		pending += decoder.end();
		const firstLine = pending.split("\n", 1)[0];
		if (!firstLine) return null;
		const header = JSON.parse(firstLine) as Record<string, unknown>;
		if (header.type !== "session" || typeof header.id !== "string") {
			return null;
		}
		return header as unknown as SessionHeader;
	} catch {
		return null;
	} finally {
		if (fd !== undefined) closeSync(fd);
	}
}

function getSessionHeaderCwd(header: SessionHeader): string | undefined {
	const cwd = (header as { cwd?: unknown }).cwd;
	return typeof cwd === "string" ? cwd : undefined;
}

function sessionCwdMatches(cwd: string | undefined, resolvedCwd: string): boolean {
	return cwd !== undefined && cwd !== "" && resolvePath(cwd) === resolvedCwd;
}

function shouldPruneResidentOnHydration(options: SessionHydrationOptions | undefined): boolean {
	return options?.residentPrune === true || process.env.PI_RESIDENT_SESSION_PRUNE === "1";
}

/** Exported for testing */
export function findMostRecentSession(sessionDir: string, cwd?: string): string | null {
	const resolvedSessionDir = normalizePath(sessionDir);
	const resolvedCwd = cwd ? resolvePath(cwd) : undefined;
	try {
		const files = readdirSync(resolvedSessionDir)
			.filter((f) => f.endsWith(".jsonl"))
			.map((f) => join(resolvedSessionDir, f))
			.map((path) => ({ path, header: readSessionHeader(path) }))
			.filter(
				(file): file is { path: string; header: SessionHeader } =>
					file.header !== null &&
					(!resolvedCwd || sessionCwdMatches(getSessionHeaderCwd(file.header), resolvedCwd)),
			)
			.map(({ path }) => ({ path, mtime: statSync(path).mtime }))
			.sort((a, b) => b.mtime.getTime() - a.mtime.getTime());

		return files[0]?.path || null;
	} catch {
		return null;
	}
}

function isMessageWithContent(message: AgentMessage): message is Message {
	return typeof (message as Message).role === "string" && "content" in message;
}

function extractTextContent(message: Message): string {
	const content = message.content;
	if (typeof content === "string") {
		return content;
	}
	return content
		.filter((block): block is TextContent => block.type === "text")
		.map((block) => block.text)
		.join(" ");
}

function getMessageActivityTime(entry: SessionMessageEntry): number | undefined {
	const message = entry.message;
	if (!isMessageWithContent(message)) return undefined;
	if (message.role !== "user" && message.role !== "assistant") return undefined;

	const msgTimestamp = (message as { timestamp?: number }).timestamp;
	if (typeof msgTimestamp === "number") {
		return msgTimestamp;
	}

	const t = new Date(entry.timestamp).getTime();
	return Number.isNaN(t) ? undefined : t;
}

async function buildSessionInfo(filePath: string): Promise<SessionInfo | null> {
	try {
		const stats = await stat(filePath);
		let header: SessionHeader | null = null;
		let messageCount = 0;
		let firstMessage = "";
		const allMessages: string[] = [];
		let name: string | undefined;
		let lastActivityTime: number | undefined;

		const rl = createInterface({
			input: createReadStream(filePath, { encoding: "utf8" }),
			crlfDelay: Infinity,
		});

		for await (const line of rl) {
			const entry = parseSessionEntryLine(line);
			if (!entry) continue;

			if (!header) {
				if (entry.type !== "session") return null;
				header = entry;
				continue;
			}

			// Extract session name (use latest, including explicit clears)
			if (entry.type === "session_info") {
				name = entry.name?.trim() || undefined;
			}

			if (entry.type !== "message") continue;
			messageCount++;

			const activityTime = getMessageActivityTime(entry);
			if (typeof activityTime === "number") {
				lastActivityTime = Math.max(lastActivityTime ?? 0, activityTime);
			}

			const message = entry.message;
			if (!isMessageWithContent(message)) continue;
			if (message.role !== "user" && message.role !== "assistant") continue;

			const textContent = extractTextContent(message);
			if (!textContent) continue;

			allMessages.push(textContent);
			if (!firstMessage && message.role === "user") {
				firstMessage = textContent;
			}
		}

		if (!header) return null;

		const cwd = typeof header.cwd === "string" ? header.cwd : "";
		const parentSessionPath = header.parentSession;
		const headerTime = typeof header.timestamp === "string" ? new Date(header.timestamp).getTime() : NaN;
		const modified =
			typeof lastActivityTime === "number" && lastActivityTime > 0
				? new Date(lastActivityTime)
				: !Number.isNaN(headerTime)
					? new Date(headerTime)
					: stats.mtime;

		return {
			path: filePath,
			id: header.id,
			cwd,
			name,
			parentSessionPath,
			created: new Date(header.timestamp),
			modified,
			messageCount,
			firstMessage: firstMessage || "(no messages)",
			allMessagesText: allMessages.join(" "),
		};
	} catch {
		return null;
	}
}

export type SessionListProgress = (loaded: number, total: number) => void;

const MAX_CONCURRENT_SESSION_INFO_LOADS = 10;

async function buildSessionInfosWithConcurrency(
	files: string[],
	onLoaded: () => void,
): Promise<(SessionInfo | null)[]> {
	const results: (SessionInfo | null)[] = new Array(files.length).fill(null);
	const inFlight = new Set<Promise<void>>();
	let nextIndex = 0;

	const startNext = (): void => {
		const index = nextIndex++;
		const file = files[index];
		if (!file) return;

		let task: Promise<void>;
		task = buildSessionInfo(file)
			.then((info) => {
				results[index] = info;
			})
			.catch(() => {
				results[index] = null;
			})
			.finally(() => {
				inFlight.delete(task);
				onLoaded();
			});
		inFlight.add(task);
	};

	while (nextIndex < files.length || inFlight.size > 0) {
		while (nextIndex < files.length && inFlight.size < MAX_CONCURRENT_SESSION_INFO_LOADS) {
			startNext();
		}
		if (inFlight.size > 0) {
			await Promise.race(inFlight);
		}
	}

	return results;
}

async function listSessionsFromDir(
	dir: string,
	onProgress?: SessionListProgress,
	progressOffset = 0,
	progressTotal?: number,
): Promise<SessionInfo[]> {
	const sessions: SessionInfo[] = [];
	if (!existsSync(dir)) {
		return sessions;
	}

	try {
		const dirEntries = await readdir(dir);
		const files = dirEntries.filter((f) => f.endsWith(".jsonl")).map((f) => join(dir, f));
		const total = progressTotal ?? files.length;

		let loaded = 0;
		const results = await buildSessionInfosWithConcurrency(files, () => {
			loaded++;
			onProgress?.(progressOffset + loaded, total);
		});
		for (const info of results) {
			if (info) {
				sessions.push(info);
			}
		}
	} catch {
		// Return empty list on error
	}

	return sessions;
}

/**
 * Manages conversation sessions as append-only trees stored in JSONL files.
 *
 * Each session entry has an id and parentId forming a tree structure. The "leaf"
 * pointer tracks the current position. Appending creates a child of the current leaf.
 * Branching moves the leaf to an earlier entry, allowing new branches without
 * modifying history.
 *
 * Use buildSessionContext() to get the resolved message list for the LLM, which
 * handles compaction summaries and follows the path from root to current leaf.
 */
export class SessionManager {
	private sessionId: string = "";
	private sessionFile: string | undefined;
	private sessionDir: string;
	private cwd: string;
	private persist: boolean;
	private flushed: boolean = false;
	private fileEntries: FileEntry[] = [];
	private byId: Map<string, SessionEntry> = new Map();
	private labelsById: Map<string, string> = new Map();
	private labelTimestampsById: Map<string, string> = new Map();
	private leafId: string | null = null;

	private constructor(
		cwd: string,
		sessionDir: string,
		sessionFile: string | undefined,
		persist: boolean,
		newSessionOptions?: NewSessionOptions,
		hydrationOptions?: SessionHydrationOptions,
	) {
		this.cwd = resolvePath(cwd);
		this.sessionDir = normalizePath(sessionDir);
		this.persist = persist;
		if (persist && this.sessionDir && !existsSync(this.sessionDir)) {
			mkdirSync(this.sessionDir, { recursive: true });
		}

		if (sessionFile) {
			this.setSessionFile(sessionFile, hydrationOptions);
		} else {
			this.newSession(newSessionOptions);
		}
	}

	/** Switch to a different session file (used for resume and branching) */
	setSessionFile(sessionFile: string, hydrationOptions: SessionHydrationOptions = {}): void {
		this.sessionFile = resolvePath(sessionFile);
		if (existsSync(this.sessionFile)) {
			const pruneOnHydration = shouldPruneResidentOnHydration(hydrationOptions);
			const headerBeforeLoad = readSessionHeader(this.sessionFile);
			const canPruneDuringLoad = pruneOnHydration && headerBeforeLoad?.version === CURRENT_SESSION_VERSION;
			const pruneLoadOptions: LoadEntriesFromFileOptions = {
				residentPrune: true,
				residentPruneOptions: hydrationOptions.residentPruneOptions,
			};

			this.fileEntries = loadEntriesFromFile(this.sessionFile, canPruneDuringLoad ? pruneLoadOptions : undefined);

			// If file was empty or corrupted (no valid header), truncate and start fresh
			// to avoid appending messages without a session header (which breaks the session)
			if (this.fileEntries.length === 0) {
				const explicitPath = this.sessionFile;
				this.newSession();
				this.sessionFile = explicitPath;
				this._rewriteFile();
				this.flushed = true;
				return;
			}

			const header = this.fileEntries.find((e) => e.type === "session") as SessionHeader | undefined;
			this.sessionId = header?.id ?? createSessionId();

			if (migrateToCurrentVersion(this.fileEntries)) {
				this._rewriteFile();
				if (pruneOnHydration) {
					this.fileEntries = loadEntriesFromFile(this.sessionFile, pruneLoadOptions);
				}
			}

			this._buildIndex();
			this.flushed = true;
		} else {
			const explicitPath = this.sessionFile;
			this.newSession();
			this.sessionFile = explicitPath; // preserve explicit path from --session flag
		}
	}

	newSession(options?: NewSessionOptions): string | undefined {
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		this.sessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: this.sessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: options?.parentSession,
		};
		this.fileEntries = [header];
		this.byId.clear();
		this.labelsById.clear();
		this.leafId = null;
		this.flushed = false;

		if (this.persist) {
			const fileTimestamp = timestamp.replace(/[:.]/g, "-");
			this.sessionFile = join(this.getSessionDir(), `${fileTimestamp}_${this.sessionId}.jsonl`);
		}
		return this.sessionFile;
	}

	private _buildIndex(): void {
		this.byId.clear();
		this.labelsById.clear();
		this.labelTimestampsById.clear();
		this.leafId = null;
		for (const entry of this.fileEntries) {
			if (entry.type === "session") continue;
			this.byId.set(entry.id, entry);
			this.leafId = entry.id;
			if (entry.type === "label") {
				if (entry.label) {
					this.labelsById.set(entry.targetId, entry.label);
					this.labelTimestampsById.set(entry.targetId, entry.timestamp);
				} else {
					this.labelsById.delete(entry.targetId);
					this.labelTimestampsById.delete(entry.targetId);
				}
			}
		}
	}

	private _rewriteFile(): void {
		if (!this.persist || !this.sessionFile) return;
		const fd = openSync(this.sessionFile, "w");
		try {
			for (const entry of this.fileEntries) {
				writeFileSync(fd, `${JSON.stringify(entry)}\n`);
			}
		} finally {
			closeSync(fd);
		}
	}

	isPersisted(): boolean {
		return this.persist;
	}

	getCwd(): string {
		return this.cwd;
	}

	getSessionDir(): string {
		return this.sessionDir;
	}

	usesDefaultSessionDir(): boolean {
		return this.sessionDir === getDefaultSessionDirPath(this.cwd);
	}

	getSessionId(): string {
		return this.sessionId;
	}

	getSessionFile(): string | undefined {
		return this.sessionFile;
	}

	getParentSession(): string | undefined {
		const header = this.fileEntries.find((entry) => entry.type === "session") as SessionHeader | undefined;
		return header?.parentSession;
	}

	_persist(entry: SessionEntry): void {
		if (!this.persist || !this.sessionFile) return;

		const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
		if (!hasAssistant) {
			if (this.flushed) {
				appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
			} else {
				// Mark as not flushed so when assistant arrives, all entries get written
				this.flushed = false;
			}
			return;
		}

		if (!this.flushed) {
			const fd = openSync(this.sessionFile, "wx");
			try {
				for (const e of this.fileEntries) {
					writeFileSync(fd, `${JSON.stringify(e)}\n`);
				}
			} finally {
				closeSync(fd);
			}
			this.flushed = true;
		} else {
			appendFileSync(this.sessionFile, `${JSON.stringify(entry)}\n`);
		}
	}

	private _appendEntry(entry: SessionEntry): void {
		this.fileEntries.push(entry);
		this.byId.set(entry.id, entry);
		this.leafId = entry.id;
		this._persist(entry);
	}

	/** Append a message as child of current leaf, then advance leaf. Returns entry id.
	 * Does not allow writing CompactionSummaryMessage and BranchSummaryMessage directly.
	 * Reason: we want these to be top-level entries in the session, not message session entries,
	 * so it is easier to find them.
	 * These need to be appended via appendCompaction() and appendBranchSummary() methods.
	 */
	appendMessage(message: Message | CustomMessage | BashExecutionMessage): string {
		const entry: SessionMessageEntry = {
			type: "message",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			message,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a thinking level change as child of current leaf, then advance leaf. Returns entry id. */
	appendThinkingLevelChange(thinkingLevel: string): string {
		const entry: ThinkingLevelChangeEntry = {
			type: "thinking_level_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			thinkingLevel,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a model change as child of current leaf, then advance leaf. Returns entry id. */
	appendModelChange(provider: string, modelId: string): string {
		const entry: ModelChangeEntry = {
			type: "model_change",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			provider,
			modelId,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a compaction summary as child of current leaf, then advance leaf. Returns entry id. */
	appendCompaction<T = unknown>(
		summary: string,
		firstKeptEntryId: string,
		tokensBefore: number,
		details?: T,
		fromHook?: boolean,
	): string {
		const entry: CompactionEntry<T> = {
			type: "compaction",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			summary,
			firstKeptEntryId,
			tokensBefore,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a custom entry (for extensions) as child of current leaf, then advance leaf. Returns entry id. */
	appendCustomEntry(customType: string, data?: unknown): string {
		const entry: CustomEntry = {
			type: "custom",
			customType,
			data,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Append a session info entry (e.g., display name). Returns entry id. */
	appendSessionInfo(name: string): string {
		const sanitizedName = name.replace(/[\r\n]+/g, " ").trim();
		const entry: SessionInfoEntry = {
			type: "session_info",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			name: sanitizedName,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/** Get the current session name from the latest session_info entry, if any. */
	getSessionName(): string | undefined {
		// Walk entries in reverse to find the latest session_info entry.
		// Empty names explicitly clear the session title.
		const entries = this.getEntries();
		for (let i = entries.length - 1; i >= 0; i--) {
			const entry = entries[i];
			if (entry.type === "session_info") {
				return entry.name?.trim() || undefined;
			}
		}
		return undefined;
	}

	/**
	 * Append a custom message entry (for extensions) that participates in LLM context.
	 * @param customType Extension identifier for filtering on reload
	 * @param content Message content (string or TextContent/ImageContent array)
	 * @param display Whether to show in TUI (true = styled display, false = hidden)
	 * @param details Optional extension-specific metadata (not sent to LLM)
	 * @returns Entry id
	 */
	appendCustomMessageEntry<T = unknown>(
		customType: string,
		content: string | (TextContent | ImageContent)[],
		display: boolean,
		details?: T,
	): string {
		const entry: CustomMessageEntry<T> = {
			type: "custom_message",
			customType,
			content,
			display,
			details,
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
		};
		this._appendEntry(entry);
		return entry.id;
	}

	// =========================================================================
	// Tree Traversal
	// =========================================================================

	getLeafId(): string | null {
		return this.leafId;
	}

	getLeafEntry(): SessionEntry | undefined {
		return this.leafId ? this.byId.get(this.leafId) : undefined;
	}

	getEntry(id: string): SessionEntry | undefined {
		return this.byId.get(id);
	}

	/**
	 * Get all direct children of an entry.
	 */
	getChildren(parentId: string): SessionEntry[] {
		const children: SessionEntry[] = [];
		for (const entry of this.byId.values()) {
			if (entry.parentId === parentId) {
				children.push(entry);
			}
		}
		return children;
	}

	/**
	 * Get the label for an entry, if any.
	 */
	getLabel(id: string): string | undefined {
		return this.labelsById.get(id);
	}

	/**
	 * Set or clear a label on an entry.
	 * Labels are user-defined markers for bookmarking/navigation.
	 * Pass undefined or empty string to clear the label.
	 */
	appendLabelChange(targetId: string, label: string | undefined): string {
		if (!this.byId.has(targetId)) {
			throw new Error(`Entry ${targetId} not found`);
		}
		const entry: LabelEntry = {
			type: "label",
			id: generateId(this.byId),
			parentId: this.leafId,
			timestamp: new Date().toISOString(),
			targetId,
			label,
		};
		this._appendEntry(entry);
		if (label) {
			this.labelsById.set(targetId, label);
			this.labelTimestampsById.set(targetId, entry.timestamp);
		} else {
			this.labelsById.delete(targetId);
			this.labelTimestampsById.delete(targetId);
		}
		return entry.id;
	}

	/**
	 * Walk from entry to root, returning all entries in path order.
	 * Includes all entry types (messages, compaction, model changes, etc.).
	 * Use buildSessionContext() to get the resolved messages for the LLM.
	 */
	getBranch(fromId?: string): SessionEntry[] {
		const path: SessionEntry[] = [];
		const startId = fromId ?? this.leafId;
		let current = startId ? this.byId.get(startId) : undefined;
		while (current) {
			path.push(current);
			current = current.parentId ? this.byId.get(current.parentId) : undefined;
		}
		path.reverse();
		return path;
	}

	/**
	 * Build the session context (what gets sent to the LLM).
	 * Uses tree traversal from current leaf.
	 */
	buildSessionContext(): SessionContext {
		return buildSessionContext(this.getEntries(), this.leafId, this.byId);
	}

	estimateResidentPayloadBytes(): number {
		return estimateResidentPayloadBytes(this.getEntries());
	}

	/**
	 * Stub resident-only payloads from the summarized span before a compaction boundary.
	 * Durable JSONL remains append-only: this method never rewrites or deletes the session file.
	 */
	pruneResidentHistoryAfterCompaction(compactionId?: string, options: ResidentPruneOptions = {}): ResidentPruneResult {
		const pruneOptions: Required<ResidentPruneOptions> = {
			stubSummarizedEntries: options.stubSummarizedEntries ?? true,
			stubToolResults: options.stubToolResults ?? true,
		};
		const payloadBytesBefore = this.estimateResidentPayloadBytes();
		const path = this.getBranch();
		const compactionIndex = compactionId
			? path.findIndex((entry) => entry.type === "compaction" && entry.id === compactionId)
			: (() => {
					for (let i = path.length - 1; i >= 0; i--) {
						if (path[i].type === "compaction") return i;
					}
					return -1;
				})();
		const compactionEntry = path[compactionIndex] as CompactionEntry | undefined;
		if (!compactionEntry || compactionEntry.type !== "compaction") {
			return {
				compactionId,
				firstKeptEntryId: undefined,
				entriesVisited: 0,
				entriesStubbed: 0,
				protectedEntries: 0,
				payloadBytesBefore,
				payloadBytesAfter: payloadBytesBefore,
				payloadBytesFreed: 0,
				jsonlUnchanged: true,
			};
		}

		const firstKeptIndex = path.findIndex((entry) => entry.id === compactionEntry.firstKeptEntryId);
		if (firstKeptIndex < 0 || firstKeptIndex >= compactionIndex) {
			return {
				compactionId: compactionEntry.id,
				firstKeptEntryId: compactionEntry.firstKeptEntryId,
				entriesVisited: 0,
				entriesStubbed: 0,
				protectedEntries: 0,
				payloadBytesBefore,
				payloadBytesAfter: payloadBytesBefore,
				payloadBytesFreed: 0,
				jsonlUnchanged: true,
			};
		}

		const candidates = path.slice(0, firstKeptIndex);
		const candidateIds = new Set(candidates.map((entry) => entry.id));
		const toolPairs = collectToolPairEntryIds(path);
		let entriesStubbed = 0;
		let protectedEntries = 0;

		for (const entry of candidates) {
			if (entryHasProtectedToolPair(entry, candidateIds, toolPairs)) {
				protectedEntries++;
				continue;
			}
			const entryBytesBefore = estimateEntryPayloadBytes(entry);
			if (stubResidentEntryPayload(entry, pruneOptions) && estimateEntryPayloadBytes(entry) < entryBytesBefore) {
				entriesStubbed++;
			}
		}

		const payloadBytesAfter = this.estimateResidentPayloadBytes();
		return {
			compactionId: compactionEntry.id,
			firstKeptEntryId: compactionEntry.firstKeptEntryId,
			entriesVisited: candidates.length,
			entriesStubbed,
			protectedEntries,
			payloadBytesBefore,
			payloadBytesAfter,
			payloadBytesFreed: Math.max(0, payloadBytesBefore - payloadBytesAfter),
			jsonlUnchanged: true,
		};
	}

	/**
	 * Get session header.
	 */
	getHeader(): SessionHeader | null {
		const h = this.fileEntries.find((e) => e.type === "session");
		return h ? (h as SessionHeader) : null;
	}

	/**
	 * Get all session entries (excludes header). Returns a shallow copy.
	 * The session is append-only: use appendXXX() to add entries, branch() to
	 * change the leaf pointer. Entries cannot be modified or deleted.
	 */
	getEntries(): SessionEntry[] {
		return this.fileEntries.filter((e): e is SessionEntry => e.type !== "session");
	}

	/**
	 * Get the session as a tree structure. Returns a shallow defensive copy of all entries.
	 * A well-formed session has exactly one root (first entry with parentId === null).
	 * Orphaned entries (broken parent chain) are also returned as roots.
	 */
	getTree(): SessionTreeNode[] {
		const entries = this.getEntries();
		const nodeMap = new Map<string, SessionTreeNode>();
		const roots: SessionTreeNode[] = [];

		// Create nodes with resolved labels
		for (const entry of entries) {
			const label = this.labelsById.get(entry.id);
			const labelTimestamp = this.labelTimestampsById.get(entry.id);
			nodeMap.set(entry.id, { entry, children: [], label, labelTimestamp });
		}

		// Build tree
		for (const entry of entries) {
			const node = nodeMap.get(entry.id)!;
			if (entry.parentId === null || entry.parentId === entry.id) {
				roots.push(node);
			} else {
				const parent = nodeMap.get(entry.parentId);
				if (parent) {
					parent.children.push(node);
				} else {
					// Orphan - treat as root
					roots.push(node);
				}
			}
		}

		// Sort children by timestamp (oldest first, newest at bottom)
		// Use iterative approach to avoid stack overflow on deep trees
		const stack: SessionTreeNode[] = [...roots];
		while (stack.length > 0) {
			const node = stack.pop()!;
			node.children.sort((a, b) => new Date(a.entry.timestamp).getTime() - new Date(b.entry.timestamp).getTime());
			stack.push(...node.children);
		}

		return roots;
	}

	// =========================================================================
	// Branching
	// =========================================================================

	/**
	 * Start a new branch from an earlier entry.
	 * Moves the leaf pointer to the specified entry. The next appendXXX() call
	 * will create a child of that entry, forming a new branch. Existing entries
	 * are not modified or deleted.
	 */
	branch(branchFromId: string): void {
		if (!this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
	}

	/**
	 * Reset the leaf pointer to null (before any entries).
	 * The next appendXXX() call will create a new root entry (parentId = null).
	 * Use this when navigating to re-edit the first user message.
	 */
	resetLeaf(): void {
		this.leafId = null;
	}

	/**
	 * Start a new branch with a summary of the abandoned path.
	 * Same as branch(), but also appends a branch_summary entry that captures
	 * context from the abandoned conversation path.
	 */
	branchWithSummary(branchFromId: string | null, summary: string, details?: unknown, fromHook?: boolean): string {
		if (branchFromId !== null && !this.byId.has(branchFromId)) {
			throw new Error(`Entry ${branchFromId} not found`);
		}
		this.leafId = branchFromId;
		const entry: BranchSummaryEntry = {
			type: "branch_summary",
			id: generateId(this.byId),
			parentId: branchFromId,
			timestamp: new Date().toISOString(),
			fromId: branchFromId ?? "root",
			summary,
			details,
			fromHook,
		};
		this._appendEntry(entry);
		return entry.id;
	}

	/**
	 * Create a new session file containing only the path from root to the specified leaf.
	 * Useful for extracting a single conversation path from a branched session.
	 * Returns the new session file path, or undefined if not persisting.
	 */
	createBranchedSession(leafId: string): string | undefined {
		const previousSessionFile = this.sessionFile;
		const residentPath = this.getBranch(leafId);
		if (residentPath.length === 0) {
			throw new Error(`Entry ${leafId} not found`);
		}
		const durablePath = previousSessionFile
			? buildBranchFromEntries(loadEntriesFromFile(previousSessionFile), leafId)
			: undefined;
		const path = durablePath ?? residentPath;

		// Filter out LabelEntry from path - we'll recreate them from the resolved map.
		// Because labels are real tree entries, later entries can be children of labels;
		// removing labels requires re-chaining the retained path to avoid orphaned subtrees.
		const pathWithoutLabels: SessionEntry[] = [];
		let pathParentId: string | null = null;
		for (const entry of path) {
			if (entry.type === "label") continue;
			pathWithoutLabels.push({ ...entry, parentId: pathParentId });
			pathParentId = entry.id;
		}

		const newSessionId = createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(this.getSessionDir(), `${fileTimestamp}_${newSessionId}.jsonl`);

		const header: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: this.cwd,
			parentSession: this.persist ? previousSessionFile : undefined,
		};

		// Collect labels for entries in the path
		const pathEntryIds = new Set(pathWithoutLabels.map((e) => e.id));
		const labelsToWrite: Array<{ targetId: string; label: string; timestamp: string }> = [];
		for (const [targetId, label] of this.labelsById) {
			if (pathEntryIds.has(targetId)) {
				labelsToWrite.push({ targetId, label, timestamp: this.labelTimestampsById.get(targetId)! });
			}
		}

		if (this.persist) {
			// Build label entries
			const lastEntryId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
			let parentId = lastEntryId;
			const labelEntries: LabelEntry[] = [];
			for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
				const labelEntry: LabelEntry = {
					type: "label",
					id: generateId(new Set(pathEntryIds)),
					parentId,
					timestamp: labelTimestamp,
					targetId,
					label,
				};
				pathEntryIds.add(labelEntry.id);
				labelEntries.push(labelEntry);
				parentId = labelEntry.id;
			}

			this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
			this.sessionId = newSessionId;
			this.sessionFile = newSessionFile;
			this._buildIndex();

			// Only write the file now if it contains an assistant message.
			// Otherwise defer to _persist(), which creates the file on the
			// first assistant response, matching the newSession() contract
			// and avoiding the duplicate-header bug when _persist()'s
			// no-assistant guard later resets flushed to false.
			const hasAssistant = this.fileEntries.some((e) => e.type === "message" && e.message.role === "assistant");
			if (hasAssistant) {
				this._rewriteFile();
				this.flushed = true;
			} else {
				this.flushed = false;
			}

			return newSessionFile;
		}

		// In-memory mode: replace current session with the path + labels
		const labelEntries: LabelEntry[] = [];
		let parentId = pathWithoutLabels[pathWithoutLabels.length - 1]?.id || null;
		for (const { targetId, label, timestamp: labelTimestamp } of labelsToWrite) {
			const labelEntry: LabelEntry = {
				type: "label",
				id: generateId(new Set([...pathEntryIds, ...labelEntries.map((e) => e.id)])),
				parentId,
				timestamp: labelTimestamp,
				targetId,
				label,
			};
			labelEntries.push(labelEntry);
			parentId = labelEntry.id;
		}
		this.fileEntries = [header, ...pathWithoutLabels, ...labelEntries];
		this.sessionId = newSessionId;
		this._buildIndex();
		return undefined;
	}

	/**
	 * Create a new session.
	 * @param cwd Working directory (stored in session header)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static create(cwd: string, sessionDir?: string, options?: NewSessionOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		return new SessionManager(cwd, dir, undefined, true, options);
	}

	/**
	 * Open a specific session file.
	 * @param path Path to session file
	 * @param sessionDir Optional session directory for /new or /branch. If omitted, derives from file's parent.
	 * @param cwdOverride Optional cwd override instead of the session header cwd.
	 */
	static open(
		path: string,
		sessionDir?: string,
		cwdOverride?: string,
		hydrationOptions?: SessionHydrationOptions,
	): SessionManager {
		const resolvedPath = resolvePath(path);
		// Extract cwd from session header if possible, otherwise use process.cwd().
		// Do not fully hydrate here; setSessionFile() owns the single full JSONL load.
		const header = readSessionHeader(resolvedPath);
		const cwd = cwdOverride ?? header?.cwd ?? process.cwd();
		// If no sessionDir provided, derive from file's parent directory
		const dir = sessionDir ? normalizePath(sessionDir) : resolve(resolvedPath, "..");
		return new SessionManager(cwd, dir, resolvedPath, true, undefined, hydrationOptions);
	}

	/**
	 * Continue the most recent session, or create new if none.
	 * @param cwd Working directory
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 */
	static continueRecent(cwd: string, sessionDir?: string, hydrationOptions?: SessionHydrationOptions): SessionManager {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const mostRecent = findMostRecentSession(dir, filterCwd ? cwd : undefined);
		if (mostRecent) {
			return new SessionManager(cwd, dir, mostRecent, true, undefined, hydrationOptions);
		}
		return new SessionManager(cwd, dir, undefined, true);
	}

	/** Create an in-memory session (no file persistence) */
	static inMemory(cwd: string = process.cwd()): SessionManager {
		return new SessionManager(cwd, "", undefined, false);
	}

	/**
	 * Fork a session from another project directory into the current project.
	 * Creates a new session in the target cwd with the full history from the source session.
	 * @param sourcePath Path to the source session file
	 * @param targetCwd Target working directory (where the new session will be stored)
	 * @param sessionDir Optional session directory. If omitted, uses default for targetCwd.
	 */
	static forkFrom(
		sourcePath: string,
		targetCwd: string,
		sessionDir?: string,
		options?: NewSessionOptions,
		hydrationOptions?: SessionHydrationOptions,
	): SessionManager {
		const resolvedSourcePath = resolvePath(sourcePath);
		const resolvedTargetCwd = resolvePath(targetCwd);
		const sourceEntries = loadEntriesFromFile(resolvedSourcePath);
		if (sourceEntries.length === 0) {
			throw new Error(`Cannot fork: source session file is empty or invalid: ${resolvedSourcePath}`);
		}

		const sourceHeader = sourceEntries.find((e) => e.type === "session") as SessionHeader | undefined;
		if (!sourceHeader) {
			throw new Error(`Cannot fork: source session has no header: ${resolvedSourcePath}`);
		}

		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(resolvedTargetCwd);
		if (!existsSync(dir)) {
			mkdirSync(dir, { recursive: true });
		}

		// Create new session file with new ID but forked content
		if (options?.id !== undefined) {
			assertValidSessionId(options.id);
		}
		const newSessionId = options?.id ?? createSessionId();
		const timestamp = new Date().toISOString();
		const fileTimestamp = timestamp.replace(/[:.]/g, "-");
		const newSessionFile = join(dir, `${fileTimestamp}_${newSessionId}.jsonl`);

		// Write new header pointing to source as parent, with updated cwd
		const newHeader: SessionHeader = {
			type: "session",
			version: CURRENT_SESSION_VERSION,
			id: newSessionId,
			timestamp,
			cwd: resolvedTargetCwd,
			parentSession: resolvedSourcePath,
		};
		writeFileSync(newSessionFile, `${JSON.stringify(newHeader)}\n`, { flag: "wx" });

		// Copy all non-header entries from source
		for (const entry of sourceEntries) {
			if (entry.type !== "session") {
				appendFileSync(newSessionFile, `${JSON.stringify(entry)}\n`);
			}
		}

		return new SessionManager(resolvedTargetCwd, dir, newSessionFile, true, undefined, hydrationOptions);
	}

	/**
	 * List all sessions for a directory.
	 * @param cwd Working directory (used to compute default session directory)
	 * @param sessionDir Optional session directory. If omitted, uses default (~/.pi/agent/sessions/<encoded-cwd>/).
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async list(cwd: string, sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]> {
		const dir = sessionDir ? normalizePath(sessionDir) : getDefaultSessionDir(cwd);
		const filterCwd = sessionDir !== undefined && dir !== getDefaultSessionDirPath(cwd);
		const resolvedCwd = resolvePath(cwd);
		const sessions = (await listSessionsFromDir(dir, onProgress)).filter(
			(session) => !filterCwd || sessionCwdMatches(session.cwd, resolvedCwd),
		);
		sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
		return sessions;
	}

	/**
	 * List all sessions across all project directories.
	 * @param onProgress Optional callback for progress updates (loaded, total)
	 */
	static async listAll(onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(sessionDir?: string, onProgress?: SessionListProgress): Promise<SessionInfo[]>;
	static async listAll(
		sessionDirOrOnProgress?: string | SessionListProgress,
		onProgress?: SessionListProgress,
	): Promise<SessionInfo[]> {
		const customSessionDir =
			typeof sessionDirOrOnProgress === "string" ? normalizePath(sessionDirOrOnProgress) : undefined;
		const progress = typeof sessionDirOrOnProgress === "function" ? sessionDirOrOnProgress : onProgress;
		if (customSessionDir) {
			const sessions = await listSessionsFromDir(customSessionDir, progress);
			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		}

		const sessionsDir = getSessionsDir();

		try {
			if (!existsSync(sessionsDir)) {
				return [];
			}
			const entries = await readdir(sessionsDir, { withFileTypes: true });
			const dirs = entries.filter((e) => e.isDirectory()).map((e) => join(sessionsDir, e.name));

			// Count total files first for accurate progress
			let totalFiles = 0;
			const dirFiles: string[][] = [];
			for (const dir of dirs) {
				try {
					const files = (await readdir(dir)).filter((f) => f.endsWith(".jsonl"));
					dirFiles.push(files.map((f) => join(dir, f)));
					totalFiles += files.length;
				} catch {
					dirFiles.push([]);
				}
			}

			// Process all files with progress tracking
			let loaded = 0;
			const sessions: SessionInfo[] = [];
			const allFiles = dirFiles.flat();

			const results = await buildSessionInfosWithConcurrency(allFiles, () => {
				loaded++;
				progress?.(loaded, totalFiles);
			});

			for (const info of results) {
				if (info) {
					sessions.push(info);
				}
			}

			sessions.sort((a, b) => b.modified.getTime() - a.modified.getTime());
			return sessions;
		} catch {
			return [];
		}
	}
}
